version: '3'
services:
  db:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  redis:
    image: "redis:7.2.4-alpine"
    volumes:
      - redis_volume:/data
    command: redis-server --appendonly yes
    ports:
      - 6379:6379

  sidekiq:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    command: bundle exec sidekiq
    volumes:
      - type: bind
        source: ./
        target: /app
    depends_on:
      - db
      - redis

volumes: 
  db:
    name: 'sidekiq-sample'
  redis_volume:
    name: 'sidekiq-sample-redis'
