FROM ruby:3.3.0

ENV LANG C.UTF-8
ENV TZ 'Asia/Tokyo'

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    postgresql-client \
    vim && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN gem update bundler
RUN bundle install --jobs=4

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
